name: Compress Images on Push to Master with Commit
on:
  push:
    branches:
      - master
    paths:
      - 'content/uploads/**.jpg'
      - 'content/uploads/**.jpeg'
      - 'content/uploads/**.png'
      - 'content/uploads/**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit changes direct to master
        run: |
          echo "Committing compressed images"
          git config --global user.email "16809252+percula@users.noreply.github.com"
          git config --global user.name "Peter"
          git diff-index --quiet HEAD || git commit -am "Compressing images"
          git push
